### ISSUE TITLE
Angular 16 zone.js:175 Uncaught TypeError: el.setAttribute is not a function 

### ISSUE THREAD

**Issue by noamamir** [angular-threejs/angular-three#33]
hi ive followed the introduction and i have the following error on angular 16, ive tried both 2.0.0-beta42 and 1.10.7 
the error: 
zone.js:175 Uncaught TypeError: el.setAttribute is not a function
    at EmulatedEncapsulationDomRenderer2.setAttribute (platform-browser.mjs:591:16)
    at EmulatedEncapsulationDomRenderer2.applyToHost (platform-browser.mjs:753:14)
    at DomRendererFactory2.createRenderer (platform-browser.mjs:459:22)
    at AnimationRendererFactory.createRenderer (animations.mjs:139:40)
    at NgtRendererFactory.createRenderer (angular-three.mjs:2013:63)
    at createRootComponentView (core.mjs:13132:54)
    at ComponentFactory.create (core.mjs:13016:35)
    at ViewContainerRef.createComponent (core.mjs:23220:47)
    at angular-three.mjs:2558:40
    at timer (zone.js:2355:41)

**Comment by RyannGalea** [comment]
I believe you need to be on Angular 18+

**Comment by nartc** [comment]
I can't reproduce this anymore on latest version. Please follow the instruction (https://angularthree.org/core/getting-started/first-scene/) again and open a new issue if you still run into issues. Thanks
